# Enable normalizations for better window management
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Simple monitor workspace assignments
[workspace-to-monitor-force-assignment]
'1' = ['main']          # Terminal (WezTerm)
'2' = ['main']          # Browser (Chrome)
'3' = ['main']          # Communication (Slack)
'4' = ['secondary']     # Secondary monitor workspace 1
'5' = ['secondary']     # Secondary monitor workspace 2



[mode.main.binding]
    # Quick launch applications
    alt-enter = '''exec-and-forget wezterm start -- tmux attach-session || tmux new-session''' 
    alt-c = '''exec-and-forget open -a "Google Chrome"'''
    alt-s = '''exec-and-forget open -a "Slack"'''
    alt-t = '''exec-and-forget open -a "Trae"'''
    
    # Basic window management
    alt-f = 'fullscreen'
    alt-space = 'layout floating tiling'
    
    # Simple window focus (vim-style)
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # Move windows
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Monitor control
    alt-tab = 'focus-monitor next'
    
    # Workspace switching (update to only use 1-5)
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5' 

    # Move windows to workspaces (update to only use 1-5)
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'

    # Reload config
    alt-shift-r = 'reload-config'
